- name: DEPLOY AS3 DEC
  hosts: localhost
  connection: local
  gather_facts: 'no'
  vars: null
  vars_files:
    - ../creds/big_creds.yaml
  tasks:
    - name: Create an AS3 Declaration
      uri:
        url: 'https://18.133.146.189/mgmt/shared/appsvcs/declare/'
        user: '{{ bigip_user }}'
        password: '{{ bigip_pass }}'
        method: POST
        body: '{{ lookup(''file'',''as3.json'') }}'
        force_basic_auth: 'yes'
        status_code: 200
        body_format: json
        validate_certs: 'no'
      register: as3_response
    - name: DEBUG OUTPUT AS3 RESPONSE
      debug:
        msg: '{{ as3_response }}'
    - name: DEBUG OUTPUT AS3 RESPONSE
      debug:
        msg: 'Content Length = {{ as3_response.content_length }}'
    - null
