---
- hosts: TNG-RTR-Others
  gather_facts: no
  connection: local
 
  tasks:

  - name: Gather The Login Credentials
    include_vars: ../Shared-Resources/credentials.yml

  - name: Define The Targets
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ Cisco['username'] }}"
        password: "{{ Cisco['password'] }}"

  - name: Disable The Routed Interface That Bridges The Hybrid Environment
    ios_config:
      provider: "{{ provider }}"
      lines:
        - "shutdown"
      parents: interface Vlan603


