---
- hosts: TCB_RTR_Prod
  gather_facts: no
  connection: local
 
  tasks:

  - name: Gather The Login Credentials
    include_vars: ../Shared-Resources/credentials.yml

  - name: Define The Target Environment
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ Cisco['username'] }}"
        password: "{{ Cisco['password'] }}"

  - name: Disable The Outside Bundle Interface of Each LTM at Both Sites
    ios_config:
      provider: "{{ provider }}"
      lines:
        - "shutdown"
        - "do write memory"
      parents: interface Port-channel2
