---
- hosts: TNG_RTR_Oth
  gather_facts: no
  connection: local
 
  tasks:

  - name: Gather The Login Credentials
    include_vars: ../Shared-Resources/credentials.yml

  - name: Define The Target Environment
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ Cisco['username'] }}"
        password: "{{ Cisco['password'] }}"

  - name: Enable The Routed Interface That Bridges The Hybrid Environment
    ios_config:
      provider: "{{ provider }}"
      lines:
        - "no shutdown"
        - "do write memory"
      parents: interface Vlan603
      # For verifying if the result meets the anticipation
      # parents: interface TenGigabitEthernet1/0/14
