---
- hosts: TCB_RTR_Oth
  gather_facts: no
  connection: local
 
  tasks:

  - name: Gather The Login Credentials
    include_vars: ../Shared-Resources/credentials.yml

  - name: Define The Target Environment
    set_fact:
      provider:
        host: "{{ inventory_hostname }}" 
        username: "{{ Cisco['username'] }}"
        password: "{{ Cisco['password'] }}"

  - name: Disable The Routed Interface That Bridges The Hybrid Environment
    ios_config:
      provider: "{{ provider }}"
      lines:
        - "shutdown"
        - "do write memory"
      parents: interface Vlan703
      # For verifying if the result meets the anticipation
      # parents: interface TenGigabitEthernet1/0/14

  # For observing the difference when "gather_facts" is enabled/disabled
  # - debug:
  #     var: hostvars[inventory_hostname]
